<?php
/**
 * Cette classe regroupe l'ensemble des commentaires
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Commentaire {

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $date_commentaire;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $commentaire;


}
?>