<?php
/**
 * 
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Connexion_User {

	/**
	 * La date de connexion de l'utilisateur à ce module
	 * @var date
	 * @access private
	 */
	private  $date_Connexion;

	/**
	 * Objet Module correspondant à une fonctionnalités sur lequel l'utilisateur est venu
	 * @var Module
	 * @access private
	 */
	private  $leModule;


}
?>