<?php
/**
 * Classe dépôt, qui représente l'ensemble des dépôts déclarer par un utilisateur.
Un dépôt à été signaler par UN utilisateur,
 et approuver ou non par PLUSIEURS utilisateurs si c'est le cas
Possède PLUSIEURS commentaires
Un dépôt peut avoir PLUSIEURS déchets
Un dépôt correspond à UN lieu
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Depot {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id_signalement;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $name;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $longitude;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $latitude;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $reported_at;

	/**
	 * 
	 * @var boolean
	 * @access private
	 */
	private  $nettoyer;

	/**
	 * Contient l'ensemble des déchets présents sur le dépôts signalé par un utilisateur
	 * @var array
	 * @access private
	 */
	private  $collection_Trash;

	/**
	 * Le user ayant signaler le dépôt
	 * @var User
	 * @access private
	 */
	private  $leUser;

	/**
	 * L'objet lieu de la classe Lieu sur lequel ce trouve le dépôt
	 * @var Lieu
	 * @access private
	 */
	private  $leLieu;

	/**
	 * Collection des commentaires effectué sur ce dépôt
	 * @var Commentaire
	 * @access private
	 */
	private  $Collection_Commentaires;

	/**
	 * Dictionnaire des users ayant approuvé ou non l'existence de ce dépôt
	 * @var Array
	 * @access private
	 */
	private  $Dictionnaire_User_Approuved;


}
?>