<?php
/**
 * Cette classe contient l'ensemble des grades octroyés ou gagner par les utilisateurs
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Grade {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $code;

	/**
	 * Ici aussi on garde en mémoire SEULEMENT le nom de l'image que l'on précéde de la constante contenant le chemin de l'image
	 * @var string
	 * @access private
	 */
	private  $image;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;


}
?>