<?php
/**
 * Permet d'instancier un lieu (commune de Saint-Denis par exemple)
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Lieu {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $code_postal;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $longitude;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $latitude;

	/**
	 * Collection des différents dépôts signalés ce trouvant sur ce lieu
	 * @var Depot
	 * @access private
	 */
	private  $Collection_Depots;


}
?>