<?php
/**
 * Cette classe contient simplement les différents modules qui peuvent être visité par un utilisateur
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Module {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $code;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;


}
?>