<?php
/**
 * Classe peremttant d'instancier un déchets
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Trash {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id_trash;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $name;

	/**
	 * Contient ici le nom de la photo, ensuite une constante vient spécifier le chemin mennt aux différentes photos de l'objet trash
	 * @var string
	 * @access private
	 */
	private  $photo;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $origin;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $kind;

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $created_at;


}
?>