<?php
/**
 * Cette classe va permettre d'instancier l'utilisateur qui n'a pas souhaité ce créer de compte
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
require_once('User.class.php');

class User_nonlog extends User {

	/**
	 * On fait en sorte que l'utilisateur soit au moins identifié via un pseudo sur l'application
	 * @var string
	 * @access private
	 */
	private  $pseudo;


}
?>