<?php
/**
 * Classe qui permet d'instancier l'utilisateur qui a souhaité ce créer un compte
Un utilisateur peut avoir PLUSIEURS grades par ailleur
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
require_once('User.class.php');

class User_log extends User {

	/**
	 * On retient juste le chemin de la photo
	 * @var string
	 * @access private
	 */
	private  $photo;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $nom;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $prenom;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $email;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $adresse;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $tel;

	/**
	 * Collection des différents grades, de l'utilisateur
	 * @var array
	 * @access private
	 */
	private  $collection_grade;


}
?>