<?php
/**
 * Classe parent user qui peut nous permettre d'avoir l'ensemble des actions effectués par CET utilisateur
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class User {

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id_user;

	/**
	 * Cet attribut permet de savoir si l'utilisateur donne ou non son constement pour laisser le choix de sauvegardé ou non les différentes actions qu'il aura effectué sur l'application
	 * @var boolean
	 * @access private
	 */
	private  $save_action;

	/**
	 * Collection des différentes actions de l'utilisateur
	 * @var Connexion_User
	 * @access private
	 */
	private  $Collection_LesConnexion;


}
?>