<?php

/**
 * Cette classe regroupe l'ensemble des commentaires
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Commentaire
{

	/**
	 * 
	 * @var date
	 * @access private
	 */
	private  $date_commentaire;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $commentaire;

	/**
	 * Construcateur de la classe commentaire
	 *
	 * @param date $date
	 * @param com $com
	 */
	public function __construct($date, $com)
	{
		$date_commentaire = $date;
		$commentaire = $com;
	}


	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 */

	 
	public function get_date_commentaire()
	{
		return $this->date_commentaire;
	}
	public function get_commentaire()
	{
		return $this->commentaire;
	}


	public function set_date_commentaire($value)
	{
		$this->date_commentaire = $value;
	}
	public function set_commentaire($value)
	{
		$this->commentaire = $value;
	}

	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
