<?php

/**
 * Cette classe contient l'ensemble des grades octroyés ou gagner par les utilisateurs
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Grade
{

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $code;

	/**
	 * Ici aussi on garde en mémoire SEULEMENT le nom de l'image que l'on précéde de la constante contenant le chemin de l'image
	 * @var string
	 * @access private
	 */
	private  $image;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $description;


	/**
	 * Simple constructeur de l'objet Grade
	 *
	 * @param string $code
	 * @param string $image
	 * @param string $libelle
	 * @param string $description
	 */
	public function __construct($code,	$image,	$libelle,	$description)
	{
		$code = $code;
		$image = $image;
		$libelle = $libelle;
		$description = $description;
	}



	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 */

	public function get_code()
	{
		return $this->code;
	}
	public function get_image()
	{
		return $this->image;
	}
	public function get_libelle()
	{
		return $this->libelle;
	}
	public function get_description()
	{
		return $this->description;
	}


	public function set_code($value)
	{
		$this->code = $value;
	}
	public function set_image($value)
	{
		$this->image = $value;
	}
	public function set_libelle($value)
	{
		$this->libelle = $value;
	}
	public function set_description($value)
	{
		$this->description = $value;
	}
	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
