<?php
/**
 * Classe connexion permettant tout simplement d'instancier un objet connexion qui permettra d'avoir un lien avec la Base De Données extérieure pour ensuite pouvoir effectuer ses requêtes si besoin
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Connexion {

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $bdd_name;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $adress;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $user;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $mdp;


	/**
	 * @access protected
	 * @param  $name 
	 * @param  $adr 
	 * @param  $user 
	 * @param  $mdp 
	 * @param  $ 
	 */

	protected  function __construct() {

			$serveur = 'localhost';
			$bdd = 'allfortrash';
			$user = 'root';
			$mdp = '';
	
			try {
				// Teste pour se co à la BDD 
				$this->connexion = new PDO("mysql:host=$serveur;dbname=$bdd;charset=utf8", $user, $mdp, array(PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION));
			} catch (Exception $e) {
				// Sinon, affiche un message d'erreur
				throw new Exception("Aucun accès à la Base De Données");
			}
		

	}


}
?>