<?php

/**
 * Permet d'instancier un lieu (commune de Saint-Denis par exemple)
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Lieu
{

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $code_postal;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $longitude;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $latitude;

	/**
	 * Collection des différents dépôts signalés ce trouvant sur ce lieu
	 * @var Depot
	 * @access private
	 */
	private  $Collection_Depots;

	public function __construct($code_postal, $libelle, $longitude, $latitude, $charger_Depot = false)
	{
		$code_postal = $code_postal;
		$libelle = $libelle;
		$longitude = $longitude;
		$latitude = $latitude;

		if ($charger_Depot) {
			$Collection_Depots = null; // REQUETE SUR LE CODE POSTAL + CONSTRUCTION DE L'OBJET DEPOT + AJOUT A NOTRE COLLECTION
		} else {
			$Collection_Depots = array(); // On en fait un tableau vide pour le moment
		}
	}



	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 */


	public function get_code_postal()
	{
		return $this->code_postal;
	}
	public function get_libelle()
	{
		return $this->libelle;
	}
	public function get_longitude()
	{
		return $this->longitude;
	}
	public function get_latitude()
	{
		return $this->latitude;
	}

	public function set_code_postal($value)
	{
		$this->code_postal = $value;
	}
	public function set_libelle($value)
	{
		$this->libelle = $value;
	}
	public function set_longitude($value)
	{
		$this->longitude = $value;
	}
	public function set_latitude($value)
	{
		$this->latitude = $value;
	}

	// Fonction pour notre collection de dépôts
	public function get_All_Depot()
	{
		return $this->Collection_Depots;
	}

	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
