<?php

/**
 * Cette classe contient simplement les différents modules qui peuvent être visité par un utilisateur
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Module
{

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $code;

	/**
	 * 
	 * @var string
	 * @access private
	 */
	private  $libelle;


	/**
	 * Constructeur de la classe Module
	 *
	 * @param string $code
	 * @param string $lib
	 */
	public function __construct($code, $lib)
	{
		$code = $code;
		$libelle = $lib;
	}



	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 */

	public function get_code()
	{
		return $this->code;
	}
	public function get_lib()
	{
		return $this->lib;
	}



	public function set_code($value)
	{
		$this->code = $value;
	}
	public function set_lib($value)
	{
		$this->lib = $value;
	}

	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
