<?php

/**
 * Classe parent user qui peut nous permettre d'avoir l'ensemble des actions effectués par CET utilisateur
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class User
{

	/**
	 * 
	 * @var int
	 * @access private
	 */
	private  $id_user;

	/**
	 * Cet attribut permet de savoir si l'utilisateur donne ou non son constement pour laisser le choix de sauvegardé ou non les différentes actions qu'il aura effectué sur l'application
	 * @var boolean
	 * @access private
	 */
	private  $save_action;



	/**
	 * Simple constructeur de notre classe mère User
	 *
	 * @param int $id_user
	 * @param boolean $save_action
	 * @param boolean $charge_All_Connexion
	 */
	public function __construct($id_user, $save_action)
	{
		$id_user = $id_user;
		$save_action = $save_action;
	}



	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ******
	 */

	public function get_id_user()
	{
		return $this->id_user;
	}
	public function get_save_action()
	{
		return $this->save_action;
	}
	public function get_Collection_LesConnexion()
	{
		return $this->Collection_LesConnexion;
	}


	public function set_id_user($value)
	{
		$this->id_user = $value;
	}
	public function set_save_action($value)
	{
		$this->save_action = $value;
	}
	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
