<?php

/**
 * Cette classe va permettre d'instancier l'utilisateur qui n'a pas souhaité ce créer de compte
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        User
 */
require_once('User.class.php');

class User_nonlog extends User
{

	/**
	 * On fait en sorte que l'utilisateur soit au moins identifié via un pseudo sur l'application
	 * @var string
	 * @access private
	 */
	private  $pseudo;

	/**
	 * Simple constructeur de notre classe dérivée User non-log
	 *
	 * @param int $id_User
	 * @param boolean $charge_connexion
	 */
	public function __construct($id_User, $charge_connexion = false)
	{
		// REQ SQL POUR RECUPERE
		// APPEL DU CONSTRUCTEUR POUR CREATION OBJET
		// AJOUT A L'ATTRIBUT PSEUDO SA VALEUR
	}



	/**
	DEBUT Fonction GET et SET
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 */
	public function get_pseudo()
	{
		return $this->pseudo;
	}

	public function set_pseudo($value)
	{
		$this->pseudo = $value;
	}

	/**
	 ****************************************************************************************************************************************
	 ********************************************************************************************************************************
	 ************************************************************************************************************************************
	 	FIN Fonction GET et SET
	 */
}
